"""initial schema

Revision ID: 6185524d46e8
Revises:
Create Date: 2026-10-02 02:17:28.029086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6185524d46e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_ref', sa.String(length=200), nullable=False),
    sa.Column('arguments_hash', sa.String(length=64), nullable=False),
    sa.Column('policy_revision', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('model_entries',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('registry_revision', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('context_limit', sa.Integer(), nullable=True),
    sa.Column('output_limit', sa.Integer(), nullable=True),
    sa.Column('capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('price_revision', sa.String(length=100), nullable=True),
    sa.Column('price_per_m_input', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('price_per_m_output', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_events_tenant_id'), 'outbox_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_topic'), 'outbox_events', ['topic'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('policy_revision', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('repository_url', sa.Text(), nullable=True),
    sa.Column('test_url', sa.Text(), nullable=True),
    sa.Column('environment_manifest', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id')
    )
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_table('memory_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('repository_ref', sa.Text(), nullable=False),
    sa.Column('source_revision', sa.String(length=64), nullable=False),
    sa.Column('fact_type', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('source_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('verification_scope', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_facts_project_id'), 'memory_facts', ['project_id'], unique=False)
    op.create_index(op.f('ix_memory_facts_tenant_id'), 'memory_facts', ['tenant_id'], unique=False)
    op.create_index('ix_memory_scope_revision', 'memory_facts', ['tenant_id', 'project_id', 'source_revision', 'status'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('report', sa.Text(), nullable=False),
    sa.Column('expected_behavior', sa.Text(), nullable=False),
    sa.Column('actual_behavior', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id')
    )
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('base_commit', sa.String(length=64), nullable=False),
    sa.Column('model_entry_id', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('verdict', sa.String(length=24), nullable=False),
    sa.Column('media_status', sa.String(length=24), nullable=False),
    sa.Column('config_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('lease_owner', sa.String(length=100), nullable=True),
    sa.Column('lease_fence', sa.Integer(), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'created_by', 'idempotency_key')
    )
    op.create_index(op.f('ix_runs_project_id'), 'runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_runs_task_id'), 'runs', ['task_id'], unique=False)
    op.create_index(op.f('ix_runs_tenant_id'), 'runs', ['tenant_id'], unique=False)
    op.create_index('ix_runs_tenant_state', 'runs', ['tenant_id', 'state', 'updated_at'], unique=False)
    op.create_table('budget_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('reserved_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('actual_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_ledger_run_id'), 'budget_ledger', ['run_id'], unique=False)
    op.create_index(op.f('ix_budget_ledger_tenant_id'), 'budget_ledger', ['tenant_id'], unique=False)
    op.create_table('run_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sequence')
    )
    op.create_index(op.f('ix_run_events_run_id'), 'run_events', ['run_id'], unique=False)
    op.create_index(op.f('ix_run_events_tenant_id'), 'run_events', ['tenant_id'], unique=False)
    op.create_table('tool_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=100), nullable=False),
    sa.Column('logical_action', sa.String(length=100), nullable=False),
    sa.Column('effect_key', sa.String(length=64), nullable=False),
    sa.Column('arguments_hash', sa.String(length=64), nullable=False),
    sa.Column('policy_result', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('receipt', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('effect_key')
    )
    op.create_index(op.f('ix_tool_actions_run_id'), 'tool_actions', ['run_id'], unique=False)
    op.create_index(op.f('ix_tool_actions_tenant_id'), 'tool_actions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_actions_tenant_id'), table_name='tool_actions')
    op.drop_index(op.f('ix_tool_actions_run_id'), table_name='tool_actions')
    op.drop_table('tool_actions')
    op.drop_index(op.f('ix_run_events_tenant_id'), table_name='run_events')
    op.drop_index(op.f('ix_run_events_run_id'), table_name='run_events')
    op.drop_table('run_events')
    op.drop_index(op.f('ix_budget_ledger_tenant_id'), table_name='budget_ledger')
    op.drop_index(op.f('ix_budget_ledger_run_id'), table_name='budget_ledger')
    op.drop_table('budget_ledger')
    op.drop_index('ix_runs_tenant_state', table_name='runs')
    op.drop_index(op.f('ix_runs_tenant_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_task_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_project_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_memory_scope_revision', table_name='memory_facts')
    op.drop_index(op.f('ix_memory_facts_tenant_id'), table_name='memory_facts')
    op.drop_index(op.f('ix_memory_facts_project_id'), table_name='memory_facts')
    op.drop_table('memory_facts')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_outbox_events_topic'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_tenant_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_table('model_entries')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
